WITH ECOLI_YEAR_MAX AS (
    SELECT YEAR(DIFFERENTIATION_DATE) 'YEAR', MAX(SIZE_OF_COLONY) 'MAX'
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(A.DIFFERENTIATION_DATE) 'YEAR', (B.MAX - A.SIZE_OF_COLONY) 'YEAR_DEV', ID
FROM ECOLI_DATA A
JOIN ECOLI_YEAR_MAX B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;
