WITH MaxColonySizePerYear AS (
    SELECT
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_COLONY_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
),
ColonyWithDeviation AS (
    SELECT
        EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS YEAR,
        e.ID,
        e.SIZE_OF_COLONY,
        m.MAX_COLONY_SIZE,
        ABS(e.SIZE_OF_COLONY - m.MAX_COLONY_SIZE) AS YEAR_DEV
    FROM
        ECOLI_DATA e
    JOIN
        MaxColonySizePerYear m ON EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) = m.YEAR
)
SELECT
    YEAR,
    YEAR_DEV,
    ID
FROM
    ColonyWithDeviation
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC;
