# vector + vector를 한 꼴이 된거라 안됨
# SELECT (
#     SELECT CODE FROM SKILLCODES WHERE NAME = "C#"
#  + SELECT CODE FROM SKILLCODES WHERE NAME = "Python");

# 이건 됨
# SELECT (99 + 1);

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
WHERE (SKILL_CODE & (SELECT sum(CODE) FROM SKILLCODES
WHERE NAME in ('C#', 'Python'))) != 0
ORDER BY ID ASC
